// generated by stringer -type=vmExit -output stringer.go; DO NOT EDIT

package vm

import "fmt"

const _vmExit_name = "exitNotexitExceptionexitReturnexitBreakexitContinueexitYieldexitSilenced"

var _vmExit_index = [...]uint8{0, 7, 20, 30, 39, 51, 60, 72}

func (i vmExit) String() string {
	if i+1 >= vmExit(len(_vmExit_index)) {
		return fmt.Sprintf("vmExit(%d)", i)
	}
	return _vmExit_name[_vmExit_index[i]:_vmExit_index[i+1]]
}
