// generated by stringer -type=vmStatus -output stringer.go; DO NOT EDIT

package vm

import "fmt"

const _vmStatus_name = "whyNotwhyExceptionwhyReturnwhyBreakwhyContinuewhyYieldwhySilenced"

var _vmStatus_index = [...]uint8{0, 6, 18, 27, 35, 46, 54, 65}

func (i vmStatus) String() string {
	if i+1 >= vmStatus(len(_vmStatus_index)) {
		return fmt.Sprintf("vmStatus(%d)", i)
	}
	return _vmStatus_name[_vmStatus_index[i]:_vmStatus_index[i+1]]
}
