// Test data generated by make_compile_test.py - do not edit

package compile

import (
	"github.com/ncw/gpython/py"
)

var compileTestData = []struct {
	in   string
	mode string // exec, eval or single
	out  py.Code
	dis  string
}{
	{"pass", "exec", py.Code{
		Argcount:       0,
		Kwonlyargcount: 0,
		Nlocals:        0,
		Stacksize:      1,
		Flags:          64,
		Code:           "\x64\x00\x00\x53",
		Consts:         []py.Object{py.None},
		Names:          []string{},
		Varnames:       []string{},
		Freevars:       []string{},
		Cellvars:       []string{},
		Filename:       "<string>",
		Name:           "<module>",
		Firstlineno:    1,
		Lnotab:         "",
	}, "  1           0 LOAD_CONST               0 (None)\n              3 RETURN_VALUE\n"},
	{"print(\"Hello World!\")", "eval", py.Code{
		Argcount:       0,
		Kwonlyargcount: 0,
		Nlocals:        0,
		Stacksize:      2,
		Flags:          64,
		Code:           "\x65\x00\x00\x64\x00\x00\x83\x01\x00\x53",
		Consts:         []py.Object{py.String("Hello World!")},
		Names:          []string{"print"},
		Varnames:       []string{},
		Freevars:       []string{},
		Cellvars:       []string{},
		Filename:       "<string>",
		Name:           "<module>",
		Firstlineno:    1,
		Lnotab:         "",
	}, "  1           0 LOAD_NAME                0 (print)\n              3 LOAD_CONST               0 ('Hello World!')\n              6 CALL_FUNCTION            1 (1 positional, 0 keyword pair)\n              9 RETURN_VALUE\n"},
}
