// Test data generated by make_symtable_test.py - do not edit

package compile

import (
	"github.com/ncw/gpython/py"
)

var symtableTestData = []struct {
	in            string
	mode          string // exec, eval or single
	out           *SymTable
	exceptionType *py.Type
	errString     string
}{
	{"1", "eval", &SymTable{
		Type:       ModuleBlock,
		Name:       "top",
		Lineno:     0,
		Optimized:  false,
		Nested:     false,
		Exec:       false,
		ImportStar: false,
		Symbols:    Symbols{},
	}, nil, ""},
}
